"""Added settings table

Revision ID: 68f0819eb63b
Revises: 
Create Date: 2018-01-27 14:24:10.004090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f0819eb63b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('autostart_enabled', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('button_enabled', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'autostart_enabled')
    op.drop_column('settings', 'button_enabled')    
    ### end Alembic commands ###
